package scorer

const FITNESS_SAME_LAB = 500
const FITNESS_DIFFERENT_LAB = -600
const FITNESS_IN_AUEB = 100
const FITNESS_IN_AUEB_MULT = 4
const FITNESS_WILL_BE_UNAVAILABLE = -100

const FITNESS_REQUESTED = 3000
const FITNESS_ABLE = 200
const FITNESS_ABLE_NOT_PREF = 100
const FITNESS_ABLE_IF_NONE = 50

const FITNESS_LAB_NOT_REQUESTED = -10
const FITNESS_LESSON_NOT_REQUESTED = -50

const FITNESS_MORE_THAN_2_HOURS = -200
const FITNESS_MORE_THAN_3_HOURS = -500
const FITNESS_LONG_STAY = -1000
const FITNESS_MORE_HOURS_PER_HOUR = -600
const FITNESS_MORE_HOURS_PER_HOUR_AF2 = -1200
const FITNESS_LESS_HOURS_PER_HOUR = -500

const FITNESS_EMPTY_HOURS = -3000